# fly.toml app configuration file generated for titanic-js on 2023-08-07T13:57:12+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "titanic-js"
primary_region = "nrt"

[build]
  dockerfile = "Dockerfile"

[http_service]
  internal_port = 8090
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]
