# fly.toml app configuration file generated for js-titanic on 2023-08-07T11:03:53+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "js-titanic"
primary_region = "nrt"

[http_service]
  internal_port = 8090
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]
